### ISSUE TITLE
possible to get rid of 'local' prefix for custom functions?

### ISSUE THREAD

**Issue by JoernT** [Jinntec/Fore#126]
@DrRataplan see any chance? Just for authoring convenience it would be good to simply write - probably just inject the prefix under the hood to avoid clashes with existing functions?

```
  <fx-function signature="now() as xs:string" type="text/javascript">
      return new Date().toLocaleTimeString();
  </fx-function>

 {now()}
```

**Comment by DrRataplan** [comment]
Oh yeah, that's possible! Just a matter of fixing up the namespace resolving in that parsing bit. On it!
