### ISSUE TITLE
incorrect link in documentation

### ISSUE THREAD

**Issue by PieterLamers** [Jinntec/Fore#172]
https://jinntec.github.io/fore-docs/getstarted/
contains a link that reads Download Fore from [https://github.com/Jinntec/Fore/releases](https://jinntec.github.io/fore-docs/getstarted/github) and unpack it to a convenient location on your disk..  the containing link is incorrect.
BTW My compliments for the overall look of the documentation!

**Comment by JoernT** [comment]
just fixed - thanks for the compliments @PieterLamers.
