### ISSUE TITLE
Color scheme suggestion for documentation

### ISSUE THREAD

**Issue by PieterLamers** [Jinntec/Fore#173]
Although the documentation looks great in general, there is one thing I would certainly change: the color of attribute values. The green on grey is very low in contrast and therefore hard to read for me. 
BTW This also goes for eXist-db documentation, and I discovered some time ago that this may have to do with the color having been derived from a dark mode color scheme. Some examples of good contrast colors for xml in light mode are the BaseX wiki pages and the Oxygen standard color scheme.

**Comment by JoernT** [comment]
yeah - agree - the green has too low contrast. Will find a better color.

**Comment by JoernT** [comment]
i made some changes that should increase readability - let me know ...
