### ISSUE TITLE
fx-bind with @constraint and alert is broken?

### ISSUE THREAD

**Issue by nverwer** [Jinntec/Fore#192]
The demo [Revalidation](https://jinntec.github.io/Fore/demo/revalidate.html) seems to be broken when using the dev version of Fore.
The alert appears when the `@constraint` is not satisfied. But when I edit the input so that the constraint is satisfied again, the alert does not go away.

The example works with
```
<script type="module"  src="https://cdn.jsdelivr.net/npm/@jinntec/fore@latest/dist/fore-dev.js"></script>
```
but it breaks when using the dev branch (commit 659aaba863c6f17f4558039f39043073de1b6a01, 24-1-2023)
```
<script type="module" src="../../resources/scripts/fore-dev.js"></script>
```

The same problem occurs with the [complete todo example](https://jinntec.github.io/fore-docs/getstarted/todo-refined/).

**Comment by JoernT** [comment]
Thanks for reporting. Will check that. Might be just a css glitch due to
recent changes .

Nico Verwer ***@***.***> schrieb am Fr., 27. Jan. 2023, 12:16:
