### ISSUE TITLE
Demo pages not loading

### ISSUE THREAD

**Issue by duncdrum** [Jinntec/Fore#204]
For many demo pages e.g. `actions.html` I get a browser error when trying to load them

To reproduce:

1. `npm i`
2. `npm run start`
3. Click on Demo and then one of the articles

Safari/Chrome
```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```

FF
```
Loading module from “http://localhost:8090/demo/demo.js” was blocked because of a disallowed MIME type (“text/plain”).
```

not sure if I was just lucky when reading demo pages the last time I opened the app or if this has been introduce recently

node 16
`dev` branch

**Comment by JoernT** [comment]
please 

`cd demo`
`npm i`

that should do the trick

**Comment by JoernT** [comment]
fixed with a postinstall in package.json

**Comment by JoernT** [comment]
see discussion #197
