### ISSUE TITLE
Debounce demo doesn't work

### ISSUE THREAD

**Issue by timathom** [Jinntec/Fore#214]
In a local installation of the latest version of Fore, the `debounce.html` demo does not perform as expected. I am able to click the button and immediate trigger a message for each click, with no 800ms delay.

However, it performs as expected in the [hosted version](https://jinntec.github.io/Fore/demo/debounce.html).

**Comment by JoernT** [comment]
Tested against dev at 11.05. and working for me. 

Can you check with lastest dev please?
