### ISSUE TITLE
fx-insert into empty parent

### ISSUE THREAD

**Issue by wolfgangmm** [Jinntec/Fore#226]
The way `fx-insert` seems to be defined now, it is not possible to insert a first child element into an empty parent, e.g.:

```xml
<fx-control ref="instance('vars')/geography-term" value-prop="checked" update-event="input">
  <label for="geographyTerm"><pb-i18n key="form.geography">Geographie / Topographie</pb-i18n></label>
  <input id="geographyTerm" type="checkbox" class="widget"/>
  <fx-insert event="value-changed"
    if="context()/text()='true'"
    ref="instance()//textClass/keywords[@scheme='https://edh.ub.uni-heidelberg.de/edep/terms']/term"
    origin="instance('templates')/term[@ref='#geography']"></fx-insert>
</fx-control>
```

only works if `@ref` points to an existing term, so we need at least one as placeholder. However, the list of terms in `keywords` will initially be empty.

**Comment by JoernT** [comment]
This can be done by using the 'context' attribute pointing to the parent
and the 'ref' pointing to the child.

Wolfgang Meier ***@***.***> schrieb am Do., 10. Aug. 2023,
13:07:
