### ISSUE TITLE
installation via npm fails with 1.7.2

### ISSUE THREAD

**Issue by line-o** [Jinntec/Fore#231]
The [postinstall script](https://github.com/Jinntec/Fore/blob/7ce5c879eefd7a8e6f12ed8707588b5152ab3d1d/package.json#L85) throws an error

```bash
; npm install @jinntec/fore
npm ERR! code 1
npm ERR! path /Users/jll/customers/eeditiones/tuttle/node_modules/@jinntec/fore
npm ERR! command failed
npm ERR! command sh -c cd demo && npm i
npm ERR! sh: line 0: cd: demo: No such file or directory
```

I tried a couple of earlier versions. The first one I found to be installable was 1.5.0

**Comment by JoernT** [comment]
fixed in 1.8.0
