### ISSUE TITLE
Tutorial to-do app: string-length constraint malfunctions

### ISSUE THREAD

**Issue by michmech** [Jinntec/Fore#240]
I've discovered something funny going on while playing around with the example to-do app in the tutorial. In [this tutorial page](https://jinntec.github.io/fore-docs/getstarted/todo-refined/), go to the last example on the page:

![image](https://github.com/Jinntec/Fore/assets/25390933/39c7f5c6-b4f7-4e8c-b102-489670aaf3cf)

Delete the text in one of the to-do items. An error message appears, as it should:

![image](https://github.com/Jinntec/Fore/assets/25390933/e43f6d24-985f-47ba-a414-955257610636)

Then add a new to-do items by clicking the _add_ button:

![image](https://github.com/Jinntec/Fore/assets/25390933/f549eef2-9ad6-423c-a9b7-d1af66260c95)

As you can see the newly added to-do item has the same error message, even though its text is _not_ empty. No matter what you do after this point -- changing the text, deleting and adding items, changing their completed state -- the first two to-do items will always show this error message.

I don't know if this is a bug in the tutorial only or in Fore itself.

**Comment by JoernT** [comment]
thanks for reporting - already got an idea why ....

**Comment by JoernT** [comment]
ok, just a CSS rule not being strong enough. However online version won't update til next release so the fix is just in dev branch for now.
