### ISSUE TITLE
fix calculation sequence - must calculate the same sequence regardless of occurrence of bindings in the document

### ISSUE THREAD

**Issue by JoernT** [Jinntec/Fore#26]
see demo/calc-order.html -> transfer into testcase 

example illustrates that the order of fx-bind elements is relevant for calculation outcome. This shouldn't be the case.

The cause is that bind that processed in one go - adding vertices and edges in one go. To fix it first all nodes need to be added to the graph and then the edges are added.

**Comment by DrRataplan** [comment]
This is fixed by #31! 
![depends](https://user-images.githubusercontent.com/5022244/119524191-b6c72c00-bd7d-11eb-949a-6cadeba835a8.png)

**Comment by JoernT** [comment]
yeah!

**Comment by JoernT** [comment]
great - works fine. Can close this.
