### ISSUE TITLE
custom function failing

### ISSUE THREAD

**Issue by JoernT** [Jinntec/Fore#279]
```
            <fx-function signature="filterProjects($lookup as xs:string, $nodes as element()*) as element()*" type="text/xpath">
                $nodes
            </fx-function>
```

This multi-param function is failing when being called. 

It still work if there's just one argument but as soon as i add the $lookup param it throws an error in evaluateXPathToString.

It's btw independent of which function type to use xpath or javascript - same outcome.

**Comment by DrRataplan** [comment]
What's the function callsite here? The eval to string is actually happening there

**Comment by DrRataplan** [comment]
What's the function callsite here? The eval to string is actually happening there. We should make a test when we fix the bug.

**Comment by DrRataplan** [comment]
The signature is `filterProjects($lookup as xs:string, $nodes as element()*) as element()*`
This is parsed with a regex to these parts:

```
[
    "filterProjects($lookup as xs:string, $nodes as element()",
    "filterProjects($lookup as xs",
    "string, $nodes as element",
    "",
    null
]``` which is very wrong.

Regex at `registerFunction.js#19` is wrong. I'll pick this up tomorrow!
