### ISSUE TITLE
handle URL params on submissions

### ISSUE THREAD

**Issue by JoernT** [Jinntec/Fore#33]
url attributes may contain template expressions like

`url="myUrl?param1={mypath}"`

This will evaluate already correctly before submitting, however the url params must be passed to iron-ajax as an object.

**Comment by DrRataplan** [comment]
My two cents would be to rewrite that to using the fetch API. It's not a complex API so rewriting fx-submission to that should be trivial.

**Comment by JoernT** [comment]
same is true for fx-instance which also use iron-ajax still
