### ISSUE TITLE
demos broken

### ISSUE THREAD

**Issue by pherk** [Jinntec/Fore#60]
months before demos worked.
interim you wrote "demos are broken" on github.
As an betterforms/eXistDB v4.x user, I am very interested in your efforts.
Now after installing with npm i and starting via npm run start, I success only on the main page (http://localhost:8090/doc/demos.html). The demos do not work because of mimetype or security issues.
Clicking on http://localhost:8090/demo/01-hi.html gives an empty page with several errors in the console:
e.g. Loading module from “http://localhost:8090/demo/node_modules/@polymer/iron-demo-helpers/demo-snippet.js” was blocked because of a disallowed MIME type (“text/plain”).
Most of them I can fix with an resolveMimeType entry in the es-dev-server.config.js but the loading of demo.js continues to fail.
What should I do?

npm run test:watch succeeds

I hope my question is appropriate for you.

thanks
Peter Herkenrath

Ubuntu 20.04, node 15.13, firefox 92

**Comment by JoernT** [comment]
Thanks for the report.

What is your OS and browser?

You mentioned a fix with resolveMimeType - would be interested to incorporate this. What are the errors after this?

**Comment by pherk** [comment]
I should mention that I have very limited javascript experience.
On my Ubuntu chrome gives the same results as firefox (errors ;-), so it's probably not the browser.
All console errors for 'Get started'  with standard config (es-dev-config.js):
>>>
Loading failed for the <script> with source “http://localhost:8090/demo/node_modules/@webcomponents/webcomponentsjs/webcomponents-loader.js”. 01-hi.html:7:1
Loading module from “http://localhost:8090/demo/node_modules/@polymer/iron-demo-helpers/demo-snippet.js” was blocked because of a disallowed MIME type (“text/plain”). 01-hi.html
Loading module from “http://localhost:8090/demo/node_modules/@polymer/iron-demo-helpers/demo-pages-shared-styles.js” was blocked because of a disallowed MIME type (“text/plain”). 01-hi.html
Loading module from “http://localhost:8090/demo/node_modules/@polymer/paper-input/paper-input.js” was blocked because of a disallowed MIME type (“text/plain”). 01-hi.html
Loading failed for the module with source “http://localhost:8090/demo/node_modules/@polymer/iron-demo-helpers/demo-snippet.js”. 01-hi.html:122:1
Loading failed for the module with source “http://localhost:8090/demo/node_modules/@polymer/iron-demo-helpers/demo-pages-shared-styles.js”. 01-hi.html:122:1
Loading failed for the module with source “http://localhost:8090/demo/node_modules/@polymer/paper-input/paper-input.js”. 01-hi.html:122:1
Loading module from “http://localhost:8090/demo/node_modules/@polymer/paper-checkbox/paper-checkbox.js” was blocked because of a disallowed MIME type (“text/plain”). 01-hi.html
Loading failed for the module with source “http://localhost:8090/demo/node_modules/@polymer/paper-checkbox/paper-checkbox.js”. 01-hi.html:122:1
Loading module from “http://localhost:8090/demo/node_modules/@polymer/paper-button/paper-button.js” was blocked because of a disallowed MIME type (“text/plain”). 01-hi.html
Loading failed for the module with source “http://localhost:8090/demo/node_modules/@polymer/paper-button/paper-button.js”. 01-hi.html:122:1
Loading failed for the module with source “http://localhost:8090/index.js”. 01-hi.html:122:1
>>>

single error remains with the following plugin:
      resolveMimeType(context) {
        // change all JS files to Javascript
        if (context.response.is('js')) {
          return 'javascript';
        }
      },
>>>
Loading failed for the <script> with source “http://localhost:8090/demo/node_modules/@webcomponents/webcomponentsjs/webcomponents-loader.js”. 01-hi.html:7:1
Loading module from “http://localhost:8090/demo/demo.js” was blocked because of a disallowed MIME type (“text/plain”).
01-hi.html
Loading failed for the module with source “http://localhost:8090/demo/demo.js”.
>>>

Peter

**Comment by grantmacken** [comment]
@JoernT 

I get a blank screen. 
View source shows markup
but the following URI are not resolving, as shown in via firefox 

```
GET https://jinntec.github.io/Fore/demo/node_modules/@webcomponents/webcomponentsjs/webcomponents-loader.js
[HTTP/2 404 Not Found 77ms]

GET https://jinntec.github.io/Fore/dist/fore-all.js
[HTTP/2 404 Not Found 66ms]

Loading module from “https://jinntec.github.io/Fore/dist/fore-all.js” was blocked because of a disallowed MIME type (“text/html”).
recalculate.html
GET https://jinntec.github.io/favicon.ico
[HTTP/2 404 Not Found 0ms]
```

**Comment by JoernT** [comment]
ok, demo branch is broken and fore-all.js is missing there. Will need to update the branch anyway to contain latest demo files and latest fore-all.js

**Comment by JoernT** [comment]
fixed demos for now. However there are limitations: submission demos do not work due to the missing server that is needed and demos will only work in modern up-to-date browsers that support the web component apis natively. Older browsers need the polyfill which is not provided in the demo files.
