### ISSUE TITLE
paths in demo.js

### ISSUE THREAD

**Issue by pherk** [Jinntec/Fore#73]
The paths to node_modules in demo/demo.js prevent running the demos in my env.
Changing to "../node_modules" makes the browser happy.

Thanks for all your efforts.
It's a great pleasure for me to see a modern successor of betterform/XForms.

Peter

(Ubuntu 20.04, node 15.13, npm 7.19, Firefox 93)

**Comment by plutext** [comment]
Hi Joern, long time no speak :-)
Same issue and resolution here.  (node v15.1.0, since v17.0.1 didn't work)
cheers .. Jason

**Comment by JoernT** [comment]
works for me now - please report if pops up again.
